#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file.

# Read the /etc/passwd file line by line.
while IFS=: read -r username password user_id home_directory shell user_info; do
# Display the information in the expected format
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $password"
done < /etc/passwd
