#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file.

# Read the /etc/passwd file line by line.
while IFS=: read -r username _ user_id _ home_directory shell user_info; do
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd
