#!/usr/bin/env bash
# This script parses the Apache log file, groups visitors by IP and HTTP status code, and displays the data in sorted order

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -r
