#!/usr/bin/env bash
# This script displays all currently running processes for all users, including those without a TTY, in a user-oriented format, showing the process hierarchy.

ps -e -o user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest
