#!/usr/bin/env bash
# This script manages the manage_my_process script.

PID_FILE="/var/run/my_process.pid"

start() {
    echo "Starting manage_my_process..."
    if [ -f "$PID_FILE" ]; then
       echo "manage_my_process is already running."
       return
    fi
    nohup /bin/bash processes_and_signals/manage-my_process & echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    echo "Stopping manage_my_process..."
    if [ -f "PID_FILE" ]; then
       kil "$(cat "$PID_FILE")"
       rm -f "$PID_FILE"
       echo "manage_my_process stopped"
    else
       echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
   start)
       start
       ;;
   stop)
      stop
      ;;
   restart)
      ;;
   *)
      echo "Usage: manage_my_process {start|stop|restart}"
      ;;
esac
