#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using the kill command 

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Kill the process silently if it is running
[ -n "$pid" ] && kill "$pid"
