#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

trap 'echo "I am invicible!!!"' SIGTERM
